FROM golang:1.23 AS build

WORKDIR /go/src/app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o /go/bin/beamlit-gateway ./gateway/main.go

FROM gcr.io/distroless/static-debian12

COPY --from=build /go/bin/beamlit-gateway /
CMD ["/beamlit-gateway"]
