FROM golang:1.23 AS build

WORKDIR /go/src/app
COPY ./gateway .

RUN go mod download
RUN go vet -v
RUN go test -v

RUN CGO_ENABLED=0 go build -o /go/bin/beamlit-gateway

FROM gcr.io/distroless/static-debian12

COPY --from=build /go/bin/beamlit-gateway /
CMD ["/beamlit-gateway"]
