{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: beamlit-gateway-class
spec:
  controllerName: {{ .Values.gateway.controllerName }}
{{- end }}
---
{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: beamlit-gateway
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: beamlit-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: In
              values:
                {{- range $i, $e := .Values.gateway.allowedNamespaces }}
                - {{ $e }}
                {{- end }}
{{- end }}
