apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{ .Values.config | toYaml | nindent 4 }}